name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [14, 16, 18]
        op-system: [ubuntu-latest, window-latest]
    runs-on: ${{ matrix.op-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: npm ci
